package com.lynch.dao.model;

import java.io.Serializable;

public class Channel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_id
     *
     * @mbggenerated
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_name
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_desc
     *
     * @mbggenerated
     */
    private String channelDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.state
     *
     * @mbggenerated
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.owner
     *
     * @mbggenerated
     */
    private Long owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table channel
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_id
     *
     * @return the value of channel.channel_id
     *
     * @mbggenerated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_id
     *
     * @param channelId the value for channel.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_name
     *
     * @return the value of channel.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_name
     *
     * @param channelName the value for channel.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_desc
     *
     * @return the value of channel.channel_desc
     *
     * @mbggenerated
     */
    public String getChannelDesc() {
        return channelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_desc
     *
     * @param channelDesc the value for channel.channel_desc
     *
     * @mbggenerated
     */
    public void setChannelDesc(String channelDesc) {
        this.channelDesc = channelDesc == null ? null : channelDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.state
     *
     * @return the value of channel.state
     *
     * @mbggenerated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.state
     *
     * @param state the value for channel.state
     *
     * @mbggenerated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.owner
     *
     * @return the value of channel.owner
     *
     * @mbggenerated
     */
    public Long getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.owner
     *
     * @param owner the value for channel.owner
     *
     * @mbggenerated
     */
    public void setOwner(Long owner) {
        this.owner = owner;
    }
}