package com.lynch.dao.mapper;

import com.lynch.dao.model.ChannelMember;
import com.lynch.dao.model.ChannelMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ChannelMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_member
     *
     * @mbggenerated
     */
    int countByExample(ChannelMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_member
     *
     * @mbggenerated
     */
    int deleteByExample(ChannelMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_member
     *
     * @mbggenerated
     */
    int insert(ChannelMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_member
     *
     * @mbggenerated
     */
    int insertSelective(ChannelMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_member
     *
     * @mbggenerated
     */
    List<ChannelMember> selectByExampleWithRowbounds(ChannelMemberExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_member
     *
     * @mbggenerated
     */
    List<ChannelMember> selectByExample(ChannelMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChannelMember record, @Param("example") ChannelMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChannelMember record, @Param("example") ChannelMemberExample example);
}